# Generated by Django 2.2 on 2019-04-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='enrollment_num',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='students',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='score3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='score4',
            field=models.IntegerField(default=0),
        ),
    ]
