# Generated by Django 2.2 on 2019-04-17 02:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_auto_20190417_0726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='user_detail',
        ),
    ]
