# Generated by Django 2.2 on 2019-04-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190417_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='vote2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='vote3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='vote4',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
