# Generated by Django 2.2 on 2019-04-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20190417_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='vote1',
            new_name='Mr_VSIT',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='vote2',
            new_name='Ms_VSIT',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='vote3',
            new_name='Popular',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='score2',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='score3',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='score4',
        ),
    ]
