# Generated by Django 2.2 on 2019-04-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190417_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Popular',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='vote4',
        ),
    ]
