# Generated by Django 2.2 on 2019-04-18 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20190417_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Mr_VSIT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrvsit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Ms_VSIT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msvsit', to=settings.AUTH_USER_MODEL),
        ),
    ]
