# Generated by Django 2.2 on 2019-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20190418_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Mr_VSIT_Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='Ms_VSIT_Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Mr_VSIT',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Ms_VSIT',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
